
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, include = TRUE, warning = FALSE, message = FALSE)
```


```{r}

packages <- 
  c(
    "fixest",
    "broom",
    "tidyverse",
    "modelsummary",
    "vtable",
    "skimr"
  )

pacman::p_load(packages, character.only = TRUE)

```

#Load Data

```{r loading data}


#Endline Census
analysis <-
  read_rds(
    file.path(
      user_path(),
      "analysis_data.rds"
    )
  )

#Microbial Contamination - IDEXX
analysis_idexx <-
  read_rds(
    file.path(
      user_path(),
      "analysis_idexx.rds"
    )
  )


#Antibiotic Resistance
analysis_abr <-
  read_rds(
    file.path(
      user_path(),
      "analysis_abr.rds"
    )
  )

#Baseline Census
cen <- read_csv(file.path(user_path(), "1_1_baseline_census.csv"))

#Data Collection Rounds (Not baseline or endline censuses)
rounds <-
  read_rds(
    file.path(
      user_path(),
      "rounds.rds"
    )
  )
#Removing baseline data from household surveys for follow-up analysis
rounds <- rounds%>%
  filter(data_round != "BL")


#Chlorine Monitoring
mon <-
  read_rds(
    file.path(
      user_path(),
      "chlorine_monitoring.rds"
    )
  )



```


#Descriptive Statistics

```{r Descriptive statistics}

#Baseline Census
cen %>%
  select(
    -c(
      block,
      panchayat_village,
      prim_source,
      ends_with("id")
    )
  ) %>%
  sumtable(
    group = "assignment",
    title  = "Baseline demographics and behavior"
  )

#Baseline Survey
bl %>%
  select(assignment,
         treat_time_5min,
         collect_resp_women,
         collect_resp_men,
         collect_resp_both,
         treat_resp_women,
         treat_resp_men,
         treat_resp_both
    )%>%
  sumtable(
    group = "assignment",
    title  = "Baseline survey demographics and behavior"
  )


#Endline Census
analysis %>%
  select(
    -c(
      block,
      panchayat_village,
      stratum,
      ends_with("id")
    )
  ) %>%
  sumtable(
    group = "assignment",
    title  = "Endline demographics and behavior"
  )


#Endline and Baseline Census
analysis_idexx %>%
  select(
    -c(
      data_round,
      pooled_round,
      sample_id_stored,
      sample_id_tap,
      block,
      panchayat_village,
      stratum,
      ends_with("id")
    )
  ) %>%
  sumtable(
    group = "assignment",
    title  = "IDEXX - Standard"
  )


#Endline and Baseline Census
analysis_abr %>%
  select(
    -c(
      data_round,
      pooled_round,
      sample_id_stored,
      sample_id_tap,
      block,
      panchayat_village,
      stratum,
      ends_with("id")
    )
  ) %>%
  sumtable(
    group = "assignment",
    title  = "IDEXX - Antibiotic Resistance"
  )


#Data collection rounds
rounds %>%
  select(
    -c(
      block,
      panchayat_village,
      village,
      village_code,
      prim_source,
      fc_stored_2,
      fc_tap_2,
      tc_tap_2,
      tc_stored_2,
      stratum,
      pooled_round,
      stored_bag_source,
      available_jjm,
      contains("sample_id"),
      ends_with("id")
    )
  ) %>%
  sumtable(
    group = "assignment",
    title  = "Data collection rounds"
  )



#Chlorine Monitoring
#By village
mon %>%
  select(
    -c(test_date,
      village_name,
    )
  ) %>%
  sumtable(
    group = "village_code",
    group.long = TRUE,
    title  = "Chlorine monitoring"
  )

#Overall
mon %>%
  select(
    -c(test_date,
      village_name,
    )
  ) %>%
  sumtable(
    title  = "Chlorine monitoring"
  )

#Commenting out so these lines do not run every time
#Long dataset
#taps, free
# mon_long%>%
#   filter(test_sample == "Tap" & free_or_total == "Free")%>%
#   select(
#     -c(free_or_total,
#       test_sample,
#       test_tap,
#       chlorine_test,
#       test_date,
#       village_name,
#     )
#   ) %>%
#   sumtable(
#     group = "village_code",
#     group.long = TRUE,
#     title  = "Chlorine monitoring - Taps"
#   )
# #taps, total
# mon_long%>%
#   filter(test_sample == "Tap" & free_or_total == "Total")%>%
#   select(
#     -c(free_or_total,
#       test_sample,
#       test_tap,
#       chlorine_test,
#       test_date,
#       village_name,
#     )
#   ) %>%
#   sumtable(
#     group = "village_code",
#     group.long = TRUE,
#     title  = "Chlorine monitoring - Taps"
#   )
# #Stored, free
# mon_long%>%
#   filter(test_sample == "Stored" & free_or_total == "Free")%>%
#   select(
#     -c(free_or_total,
#       test_sample,
#       test_tap,
#       chlorine_test,
#       test_date,
#       village_name,
#     )
#   ) %>%
#   sumtable(
#     group = "village_code",
#     group.long = TRUE,
#     title  = "Chlorine monitoring - Stored"
#   )
# #Stored, total
# mon_long%>%
#   filter(test_sample == "Stored" & free_or_total == "Total")%>%
#   select(
#     -c(free_or_total,
#       test_sample,
#       test_tap,
#       chlorine_test,
#       test_date,
#       village_name,
#     )
#   ) %>%
#   sumtable(
#     #group = "village_code",
#     group.long = TRUE,
#     title  = "Chlorine monitoring - Stored"
#   )




```


# Treatment Effect


```{r Endline treatment effect}


# Data -------------------------------------------------------------------------

#Specifying outcomes
outcomes <-
  c(
    "Taps as Primary Source" = "prim_source_jjm",
    "Use a Secondary Source" = "sec_source",
    "Drink Tap Water" = "jjm_drinking",
    "Treat Water" = "water_treat_binary",
    "Treat Water > 5 min" = "time_spent_treat_5",
    "Reported Water Taste/Smell Issue" = "tap_issues_taste"
  )


el_village <-
  analysis %>%
  group_by(village, block, panchayat_village, stratum, assignment) %>%
  summarise(
    across(
      c(outcomes) %>% unname,
      ~ sum(., na.rm = TRUE)
    ),
    across(
      ends_with("_bl"),
      ~ unique(.)
    ),
    N = n()
   )



# Running regression models -----------------------------------------------------

el_models <-
   outcomes %>%
       map(
        ~ feglm(
          paste(., "~ assignment + offset(log(N)) +", paste0(., "_bl"))%>%as.formula(),
          data = el_village,
          family = poisson,
          se = 'iid'
        )
      )


el_models%>%
   modelsummary(
    exponentiate = TRUE,
    coef_rename = c("assignmentTreatment" = "Treatment"),
    coef_omit = "^(?!.*Treatment)",
    gof_omit = "IC|R2|RMSE",
    estimate  = "{estimate} [{conf.low}, {conf.high}]",
    statistic = NULL,
    shape = model ~ term + statistic,
    add_columns = data.frame("N"= map(., ~.x$nobs) %>% unlist %>% round)
  )





```


```{r Microbial contamination treatment effect}



#Setting outcomes
outcomes <-
  c(
    "Presence of Total Coliform at Taps"= "cf_pa_tap",
    "Presence of E. coli at Taps"= "ec_pa_tap",
    "Presence of Total Coliform in Stored Water"= "cf_pa_stored",
    "Presence of E. coli in Stored Water"= "ec_pa_stored"
    
  )


#Prepping village level data
idexx_village <-
  analysis_idexx %>%
  group_by(village, block, panchayat_village, stratum, assignment) %>%
  summarise(
    across(
      c(outcomes) %>% unname,
      ~ sum(., na.rm = TRUE)
    ),
    across(
      ends_with("_bl"),
      ~ unique(.)
    ),
    N = n()
  )



# Running regression models -----------------------------------------------------


# Poisson Regression ----------------------------------------------------------------

idexx_models <-
   outcomes %>%
       map(
        ~ feglm(
          paste(., "~ assignment + offset(log(N)) +", paste0(., "_bl"))%>%as.formula(),
          data = idexx_village,
          family = poisson,
          se = 'iid'
        )
      )


idexx_models%>%
   modelsummary(
    exponentiate = TRUE,
    coef_rename = c("assignmentTreatment" = "Treatment"),
    coef_omit = "^(?!.*Treatment)",
    gof_omit = "IC|R2|RMSE",
    estimate  = "{estimate} [{conf.low}, {conf.high}]",
    statistic = NULL,
    shape = model ~ term + statistic,
    add_columns = data.frame("N"= map(., ~.x$nobs) %>% unlist() %>% round())
  )


#Linear Regression ----------------------------------------------------------

#Setting outcomes
outcomes <-
  c(
    "Log10 MPN Total Coliform at Taps"= "cf_log_tap",
    "Log10 MPN E. coli at Taps"= "ec_log_tap",
    "Log10 MPN Total Coliform in Stored Water"= "cf_log_stored",
    "Log10 MPN E. coli in Stored Water"= "ec_log_stored"
  )


#Individual - baseline control
idexx_model_lm <-
   outcomes %>%
  map(
    ~ list(
     paste(., "~ assignment  +", paste0(., "_bl"))
     )%>%
      map(~ as.formula(.)) %>%
       map(
        ~ feols(
          fml = .,
          data = analysis_idexx,
          cluster = ~ village
        )
      )
  )


idexx_model_lm <-
   outcomes %>%
       map(
        ~ feols(
          paste(., "~ assignment +", paste0(., "_bl"))%>%as.formula(),
         data = analysis_idexx,
         cluster = ~ village
        )
      )

idexx_model_lm%>%
   modelsummary(
    exponentiate = FALSE,
    coef_rename = c("assignmentTreatment" = "Treatment"),
    coef_omit = "^(?!.*Treatment)",
    gof_omit = "IC|R2|RMSE",
    estimate  = "{estimate} [{conf.low}, {conf.high}]",
    statistic = "p.value",
    shape = model ~ term + statistic,
    add_columns = data.frame("N"= map(., ~.x$nobs) %>% unlist() %>% round())
  )


```



```{r Antibiotic resistant bacteria treatment effect}



#Setting outcomes
outcomes <-
  c(
    "Presence of Antibiotic Resistant E. coli at Taps"= "ec_pa_abr_tap",
    "Presence of Antibiotic Resistant E. coli in Stored Water"= "ec_pa_abr_stored"
    
  )


#Prepping village level data
abr_village <-
  analysis_abr %>%
  group_by(village, block, panchayat_village, stratum, assignment) %>%
  summarise(
    across(
      c(outcomes) %>% unname,
      ~ sum(., na.rm = TRUE)
    ),
    across(
      ends_with("_bl"),
      ~ unique(.)
    ),
    N = n()
  )


# Running regression models -----------------------------------------------------


# Village level ----------------------------------------------------------------

abr_models <-
   outcomes %>%
       map(
        ~ feglm(
          paste(., "~ assignment + offset(log(N)) +", paste0(., "_bl"))%>%as.formula(),
          data = abr_village,
          family = poisson,
          se = 'iid'
        )
      )



abr_models%>%
   modelsummary(
    exponentiate = TRUE,
    coef_rename = c("assignmentTreatment" = "Treatment"),
    coef_omit = "^(?!.*Treatment)",
    gof_omit = "IC|R2|RMSE",
    estimate  = "{estimate} [{conf.low}, {conf.high}]",
    statistic = NULL,
    shape = model ~ term + statistic,
    add_columns = data.frame("N"= map(., ~.x$nobs) %>% unlist() %>% round())
  )



```




```{r forestplot}


all_coefs <-
  c(
    el_models,
    abr_models,
    idexx_models
    
  ) %>%
  map(
    ~ tidy(
      .,
      conf.int = TRUE
    ) %>%
      filter(term == "assignmentTreatment")
  ) %>% 
  bind_rows(.id = "outcome") %>%
  mutate(p_char = ifelse(p.value < 0.001, "< 0.001",
    as.character(round(p.value, 3))
  )
  )%>%
  mutate(
    across(
      where(is.numeric),
      ~ round(exp(.), 3)
    ),
    variable_type = 
      if_else(
        str_detect(outcome, "Presence"),
        "Water Quality Outcome",
        "Behavioral Outcome"
    ),
    order = row_number(),
    outcome =
      factor(
        order,
        labels = outcome,
        ordered = TRUE
      )
  )



#Reordering
all_coefs$outcome <- factor(all_coefs$outcome, levels =
                                            c(
             "Treat Water > 5 min",
             "Reported Water Taste/Smell Issue",
             "Treat Water",
             "Drink Tap Water",
              "Use a Secondary Source",
             "Taps as Primary Source",
             "Presence of Antibiotic Resistant E. coli in Stored Water",
              "Presence of Antibiotic Resistant E. coli at Taps",
             "Presence of E. coli in Stored Water",
             "Presence of Total Coliform in Stored Water",
             "Presence of E. coli at Taps",
             "Presence of Total Coliform at Taps"
             ))



#Creating PR (95% CI) label to be shown on plot
all_coefs <- all_coefs%>%
  mutate(estimate_label = paste0(round(estimate, 2), " (", round(conf.low, 2), ", ", round(conf.high, 2), ")"))

p_forestplot <- 
  all_coefs %>%
  filter(
    !(outcome  %in% c("Presence of Antibiotic Resistant E. coli at Taps", "Reported Water Taste/Smell Issue")) 
  ) %>%
  # Main plot
  ggplot(
    aes(x = estimate, y = outcome, xmin = conf.low, xmax = conf.high)
  ) +
  geom_point(aes(color = variable_type), size = 2
  ) +  
  geom_errorbarh(aes(color = variable_type), height = 0.2) + 
  # Dashed line at x = 1 (null Risk Ratio)
  geom_vline(xintercept = 1, linetype = "dashed", color = "black"
  ) +
  scale_x_continuous(
    limits = c(0.12, 7),
    trans = 'log10',
    breaks = c(0.00, 0.25, 0.5, 0.75, 1.00, 1.25)
  ) +
  scale_color_manual(
    values = c(
      "Water Quality Outcome" = "#00008B", 
      "Behavioral Outcome" = "#EEA944"
    )
  ) +
  labs(
    x = "Prevalence Ratio", 
    y = "Outcome"
  ) + 
  # Theme
  theme_classic() +
  theme(
    legend.position = "right",
    legend.title = element_blank(),
    axis.text.y = element_text(size = 10), 
    axis.title.y = element_text(size = 13),
    axis.title.x = element_text(size = 13),
    axis.ticks.y = element_blank()
  ) +
  # Annotations
  geom_text(aes(label = estimate_label, x = max(conf.high) + 0.7), hjust = 0, size = 3) +
  geom_text(aes(label = p_char, x = max(conf.high) + 3),hjust = 0,size = 3) +
  geom_text(aes(label = "20", x = max(conf.high) + 5
    ), hjust = 0, size = 3)


# Add horizontal lines between levels of outcomes to create separation
y_levels <- levels(factor(all_coefs$outcome))
y_positions <- seq_along(y_levels) - 0.5
for (y in y_positions) {
  p_forestplot <- p_forestplot + geom_hline(yintercept = y, color = "darkgrey", linetype = "solid", linewidth = 0.5)
}

#p_forestplot


# ggsave(filename = "forestplot_v3.pdf", path = (paste0(github_path(), "/3_manuscript/figures")), dpi = 1080, width = 13, height = 6, units = "in")


```









# Manuscript Revision 3 - 12/16/2025

Updating with additional results below to be stored in the SI.

```{r Microbial Contamination vs Chlorine Concentrations}

#Using rounds dataset
#Filter for paired E. coli and chlorine measurements
rounds <- rounds%>%
  filter(is.na(ec_pa_tap) == FALSE |
           is.na(ec_pa_stored) == FALSE)
#table(rounds$data_round) #Checking number of household per round

#------------------------------------------------
# Figures
#------------------------------------------------


#Generate figures comparing free chlorine concentrations (mg/L) vs E. coli MPN/100 mL
#For stored and tap water

#Tap water
p_cl_vs_ec_tap <- rounds%>%
  ggplot() +
  geom_point(aes(x = fc_tap_avg, y = ec_log_tap, colour = assignment)) +
  geom_hline(aes(yintercept = -0.01), lty = 2, color = "#FF474C")+ #Placing detection threshold
  geom_text(aes(x = 1.7, y = 0, label = "Detection Threshold (>0 MPN/100 mL)"),
             nudge_y = 0.1, color = "#FF474C", size = 3)+
  scale_y_continuous(
                     limits = c(-0.5, 4),
                     expand = c(0,0)
                     )+
  scale_x_continuous(limits = c(0,2.2), breaks = c(0.2, 0.4, 0.6, 0.8, 1.0, 1.2, 1.4, 1.6, 1.8, 2.0))+
  scale_fill_brewer(palette = "Pastel1")+
  labs(x = "Free Chlorine Concentration (mg/L)", 
       y = 'log10(MPN/100 mL)',
       color = "Assignment",
       title = "",
       caption = ""
       )+
  theme_classic() + 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1),
        plot.title = element_text(size = 2))

p_cl_vs_ec_tap

ggsave(filename = "manuscript_chlorine_dose-response_tap_v1.pdf", path = (paste0(github_path(), "/3_manuscript/figures")), dpi = 1080, width = 3, height = 3, units = "in", scale = 2)

#Stored water
p_cl_vs_ec_stored <- rounds%>%
  ggplot() +
  geom_point(aes(x = fc_stored_avg, y = ec_log_stored, colour = assignment)) +
  geom_hline(aes(yintercept = -0.01), lty = 2, color = "#FF474C")+ #Placing detection threshold
  geom_text(aes(x = 1.7, y = 0, label = "Detection Threshold (>0 MPN/100 mL)"),
             nudge_y = 0.1, color = "#FF474C", size = 3)+
  scale_y_continuous(
                     limits = c(-0.5, 4),
                     expand = c(0,0)
                     )+
  scale_x_continuous(limits = c(0,2.2), breaks = c(0.2, 0.4, 0.6, 0.8, 1.0, 1.2, 1.4, 1.6, 1.8, 2.0))+
  scale_fill_brewer(palette = "Pastel1")+
  labs(x = "Free Chlorine Concentration (mg/L)", 
       y = 'log10(MPN/100 mL)',
       color = "Assignment",
       title = "",
       caption = ""
       )+
  theme_classic() + 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1),
        plot.title = element_text(size = 2))

p_cl_vs_ec_stored

ggsave(filename = "manuscript_chlorine_dose-response_stored_v1.pdf", path = (paste0(github_path(), "/3_manuscript/figures")), dpi = 1080, width = 3, height = 3, units = "in", scale = 2)



#------------------------------------------------
# Regression Models
#------------------------------------------------

# Tap Water

#Setting outcomes
outcomes <-
  c(
    "Presence of Total Coliform at Taps"= "cf_pa_tap",
    "Presence of E. coli at Taps"= "ec_pa_tap"#,
    # "Presence of Total Coliform in Stored Water"= "cf_pa_stored",
    # "Presence of E. coli in Stored Water"= "ec_pa_stored"
  )


# Running regression models -----------------------------------------------------
# Poisson Regression ----------------------------------------------------------------
rounds_sub <- rounds%>%
  mutate(fc_tap_scaled = fc_tap_avg*10)%>% #Can I do this?
  filter(fc_tap_avg > 0.1) #Filtering for positive samples only! Want to understand relationship as dosing increases, not affected by no-dose events.

#Unlike regression models above, this model does not average results at the village level since I am looking at e. coli ~ free chlorine concentrations
rounds_models_tap <-
   outcomes %>%
       map(
        ~ feglm(
          paste(., "~ fc_tap_scaled")%>%as.formula(),
          data = rounds_sub,
          family = poisson,
          cluster = ~ village,
          se = 'cluster'
        )
      )


rounds_models_tap%>%
   modelsummary(
    exponentiate = TRUE,
    #coef_rename = c("assignmentTreatment" = "Treatment"),
    #coef_omit = "^(?!.*Treatment)",
    gof_omit = "IC|R2|RMSE",
    estimate  = "{estimate} [{conf.low}, {conf.high}]",
    statistic = NULL,
    shape = model ~ term + statistic,
    add_columns = data.frame("N"= map(., ~.x$nobs) %>% unlist() %>% round())
  )


#Linear Regression - tap water ----------------------------------------------------------

#Setting outcomes
outcomes <-
  c(
    "Log10 MPN Total Coliform at Taps"= "cf_log_tap",
    "Log10 MPN E. coli at Taps"= "ec_log_tap"#,
    # "Log10 MPN Total Coliform in Stored Water"= "cf_log_stored",
    # "Log10 MPN E. coli in Stored Water"= "ec_log_stored"
  )


#Individual
rounds_model_lm <-
  outcomes %>%
       map(
        ~ feols(
          paste(., "~ fc_tap_scaled")%>%as.formula(),
          data = rounds_sub,
          cluster = ~ village,
          se = 'cluster'
        )
      )
  

rounds_model_lm%>%
   modelsummary(
    exponentiate = FALSE,
    # coef_rename = c("assignmentTreatment" = "Treatment"),
    # coef_omit = "^(?!.*Treatment)",
    gof_omit = "IC|R2|RMSE",
    estimate  = "{estimate} [{conf.low}, {conf.high}]",
    statistic = "p.value",
    shape = model ~ term + statistic,
    add_columns = data.frame("N"= map(., ~.x$nobs) %>% unlist() %>% round())
  )





#Stored Water


#Setting outcomes
outcomes <-
  c(
    # "Presence of Total Coliform at Taps"= "cf_pa_tap",
    # "Presence of E. coli at Taps"= "ec_pa_tap"#,
     "Presence of Total Coliform in Stored Water"= "cf_pa_stored",
     "Presence of E. coli in Stored Water"= "ec_pa_stored"
  )


# Running regression models -----------------------------------------------------
# Poisson Regression ----------------------------------------------------------------
rounds_sub <- rounds%>%
  mutate(fc_stored_scaled = fc_stored_avg*10)%>% #Can I do this?
  filter(fc_stored_avg > 0.1) #Filtering for positive samples only! Want to understand relationship as dosing increases, not affected by no-dose events.


#Unlike regression models above, this model does not average results at the village level since I am looking at e. coli ~ free chlorine concentrations
rounds_models_stored <-
   outcomes %>%
       map(
        ~ feglm(
          paste(., "~ fc_stored_scaled")%>%as.formula(),
          data = rounds_sub,
          family = poisson,
          cluster = ~ village,
          se = 'cluster'
        )
      )


rounds_models_stored%>%
   modelsummary(
    exponentiate = TRUE,
    #coef_rename = c("assignmentTreatment" = "Treatment"),
    #coef_omit = "^(?!.*Treatment)",
    gof_omit = "IC|R2|RMSE",
    estimate  = "{estimate} [{conf.low}, {conf.high}]",
    statistic = NULL,
    shape = model ~ term + statistic,
    add_columns = data.frame("N"= map(., ~.x$nobs) %>% unlist() %>% round())
  )




#--------------------------------------------------------------------
# Generating Forestplot
#--------------------------------------------------------------------

all_coefs <-
  c(
    rounds_models_tap,
    rounds_models_stored
  ) %>%
  map(
    ~ tidy(
      .,
      conf.int = TRUE
    ) %>%
      filter(term == "fc_tap_scaled" | term == "fc_stored_scaled")
  ) %>% 
  bind_rows(.id = "outcome") %>%
  mutate(p_char = ifelse(p.value < 0.001, "< 0.001",
    as.character(round(p.value, 3))
  )
  )%>%
  mutate(
    across(
      where(is.numeric),
      ~ round(exp(.), 3)
    ),
    variable_type = 
      if_else(
        str_detect(outcome, "Presence"),
        "Water Quality Outcome",
        "Other Outcome"
    ),
    order = row_number(),
    outcome =
      factor(
        order,
        labels = outcome,
        ordered = TRUE
      )
  )


#Reordering outcomes
all_coefs$outcome <- factor(all_coefs$outcome, levels =
                                            c(
             "Presence of E. coli in Stored Water",
             "Presence of Total Coliform in Stored Water",
             "Presence of E. coli at Taps",
             "Presence of Total Coliform at Taps"
             ))

#Creating PR (95% CI) label to be shown on plot
all_coefs <- all_coefs%>%
  mutate(estimate_label = paste0(round(estimate, 2), " (", round(conf.low, 2), ", ", round(conf.high, 2), ")"))

p_forestplot <- 
  all_coefs %>%
  # Main plot
  ggplot(
    aes(x = estimate, y = outcome, xmin = conf.low, xmax = conf.high)
  ) +
  geom_point(aes(color = variable_type), size = 2
  ) +  
  geom_errorbarh(aes(color = variable_type), height = 0.2) + 
  # Dashed line at x = 1 (null Risk Ratio)
  geom_vline(xintercept = 1, linetype = "dashed", color = "black"
  ) +
  scale_x_continuous(
    limits = c(0.12, 7),
    trans = 'log10',
    breaks = c(0.00, 0.25, 0.5, 0.75, 1.00, 1.25)
  ) +
  scale_color_manual(
    values = c(
      "Water Quality Outcome" = "#00008B", 
      "Behavioral Outcome" = "#EEA944"
    )
  ) +
  labs(
    x = "Prevalence Ratio", 
    y = "Outcome"
  ) + 
  # Theme
  theme_classic() +
  theme(
    legend.position = "right",
    legend.title = element_blank(),
    axis.text.y = element_text(size = 10), 
    axis.title.y = element_text(size = 13),
    axis.title.x = element_text(size = 13),
    axis.ticks.y = element_blank()
  ) +
  # Annotations
  geom_text(aes(label = estimate_label, x = max(conf.high) + 0.7), hjust = 0, size = 3) +
  geom_text(aes(label = p_char, x = max(conf.high) + 3),hjust = 0,size = 3) +
  geom_text(aes(label = " ", x = max(conf.high) + 5
    ), hjust = 0, size = 3)


# Add horizontal lines between levels of outcomes to create separation
y_levels <- levels(factor(all_coefs$outcome))
y_positions <- seq_along(y_levels) - 0.5
for (y in y_positions) {
  p_forestplot <- p_forestplot + geom_hline(yintercept = y, color = "darkgrey", linetype = "solid", linewidth = 0.5)
}

p_forestplot


ggsave(filename = "forestplot_dose-response_v2.pdf", path = (paste0(github_path(), "/3_manuscript/figures")), dpi = 1080, width = 13, height = 4, units = "in")



```



```{r Additional Chlorine concentration analyses}

# Creating time series figure of average free chlorine concentrations over the study period.

#Create a 2-week variable
mon_summary <- mon_long%>%
  filter(test_sample == "Tap")%>% #Filtering only for tap water
  mutate(test_week = floor_date(test_date - days(as.numeric(test_date - ymd("2024-01-01")) %% 14),
          unit = "day"))%>% #Selecting weeks on a bi-weekly basis
  filter(test_week > ymd("2024-02-01")) #Filtering for intervention launch

# Group by week and calculate the average concentration
mon_summary <- mon_summary%>%
  group_by(test_week, free_or_total)%>%
  summarise(avg_concentration = mean(chlorine_concentration, na.rm = TRUE),
            se_concentration = sd(chlorine_concentration, na.rm = TRUE) / sqrt(n()),
            lower_ci = avg_concentration - qt(0.975, df = n() - 1) * se_concentration,
            upper_ci = avg_concentration + qt(0.975, df = n() - 1) * se_concentration,
            cl_presence = round((sum(cl_pa == 1) / n()) * 100, 1),
            lower_ci_pa = (sum(cl_pa == 1) / n()) * 100 -
              (qt(0.975, n() - 1) * sd(cl_pa*100)/sqrt(n())), #Can I use a 95% CI on presence/absence data?
            upper_ci_pa = (sum(cl_pa == 1) / n()) * 100 +
              (qt(0.975, n() - 1) * sd(cl_pa*100)/sqrt(n())),
            sample_size = n()
            )%>%
  # Correcting negative lower CI values to be 0 instead
  mutate(lower_ci_pa = case_when(lower_ci_pa < 0 ~ 0,
                                     lower_ci_pa >= 0 ~ lower_ci_pa))%>%
  mutate(upper_ci_pa = case_when(upper_ci_pa > 100 ~ 100,
                                     upper_ci_pa <= 100 ~ upper_ci_pa))%>%
  mutate(lower_ci = ifelse(lower_ci < 0, 0, lower_ci))



#Creating time series for presence/absence
p_time_series_1 <- mon_summary%>%
  filter(free_or_total == "Free")%>%
  ggplot() + 
   geom_errorbar(aes(x = test_week, ymin = lower_ci_pa, ymax = upper_ci_pa),
                 width = 2) + #Does not include robust standard errors for village clustering
  geom_point(aes(x = test_week, y = cl_presence), size = 3)+
  geom_path(aes(x = test_week, y = cl_presence)) + #Geom path makes the plot cluttered
  geom_vline(aes(xintercept = ymd("2024-02-01")), lty = 2, color = "#FF474C")+ #Placing intervention start date
    geom_vline(aes(xintercept = ymd("2024-07-01")), lty = 2, color = "darkblue")+ #Placing monsoon start date
  geom_vline(aes(xintercept = ymd("2024-08-20")), lty = 2, color = "darkgreen")+ #Placing target dose change date
  # geom_text(aes(x = ymd("2024-02-01"), y = 80, label = "Intervention Start"),
  #           nudge_x = -25, color = "#FF474C")+
  scale_y_continuous(
                     limits = c(0, 105),
                     expand = c(0,0)
                     )+
  scale_x_date(limits = c(ymd("2023-10-03"), ymd("2024-10-15")),
        date_breaks = "1 month",   # Adds more frequent x-axis breaks (monthly)
        date_labels = "%b")+
  scale_fill_brewer(palette = "Pastel1")+
  labs(x = "Date", 
       y = '% of tap samples positive for chlorine (>0.1 mg/L)',
       color = "Assignment",
       title = "",
       caption = ""
       #title = expression(paste(italic("E. coli"), " r3 - Presence in Tap and Stored Drinking Water in Odisha (N = 166)"))
       )+
  theme_classic() + 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1),
        plot.title = element_text(size = 2))


p_time_series_1


#Creating time series for average concentrations
p_time_series_2 <- mon_summary%>%
  filter(free_or_total == "Free")%>%
  ggplot() + 
   geom_errorbar(aes(x = test_week, ymin = lower_ci, ymax = upper_ci),
                 width = 2) + #Does not include robust standard errors for village clustering
  geom_point(aes(x = test_week, y = avg_concentration), size = 3)+
  geom_path(aes(x = test_week, y = avg_concentration)) + #Geom path makes the plot cluttered
  geom_vline(aes(xintercept = ymd("2024-02-01")), lty = 2, color = "#FF474C")+ #Placing intervention start date
    geom_vline(aes(xintercept = ymd("2024-07-01")), lty = 2, color = "darkblue")+ #Placing monsoon start date
  geom_vline(aes(xintercept = ymd("2024-08-20")), lty = 2, color = "darkgreen")+ #Placing target dose change date
  # geom_text(aes(x = ymd("2024-02-01"), y = 80, label = "Intervention Start"),
  #           nudge_x = -25, color = "#FF474C")+
  scale_y_continuous(
                     limits = c(0, 1.0),
                     breaks = c(0.1, 0.2, 0.3, 0.4,
                                0.5, 0.6, 0.7, 0.8, 0.9, 1.0),
                     expand = c(0,0)
                     )+
  scale_x_date(limits = c(ymd("2024-01-29"), ymd("2024-10-10")),
        date_breaks = "1 month",
        date_labels = "%b")+
  scale_fill_brewer(palette = "Pastel1")+
  labs(x = "Date", 
       y = 'Average Free Chlorine Concentration (mg/L)',
       color = "Assignment",
       title = "",
       caption = ""
       )+
  theme_classic() + 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1),
        plot.title = element_text(size = 2))


p_time_series_2

ggsave(filename = "time_series_avg_conc_v1.pdf", path = (paste0(github_path(), "/3_manuscript/figures")), dpi = 1080, width = 6, height = 3, units = "in", scale = 1.3)



#--------------------------------------------------------------------------



#Comparing tap and stored drinking water chlorine concentrations in plot

#----------------------------------------------------------
# Figures
#----------------------------------------------------------

#Tap water vs stored water chlorine concentrations
p_tap_vs_stored <- rounds%>%
  ggplot() +
  geom_point(aes(x = fc_tap_avg, y = fc_stored_avg, colour = assignment)) +
  geom_hline(aes(yintercept = 0.2), lty = 2, color = "#FF474C")+ #Placing detection threshold
  geom_text(aes(x = 1.7, y = 0, label = "Detection Threshold (>0 MPN/100 mL)"),
             nudge_y = 0.1, color = "#FF474C", size = 3)+
  scale_y_continuous(
                     limits = c(0, 2.2),
                     breaks = c(0.2, 0.4, 0.6, 0.8, 1.0, 1.2, 1.4, 1.6, 1.8, 2.0),
                     expand = c(0,0)
                     )+
  scale_x_continuous(limits = c(0,2.2), breaks = c(0.2, 0.4, 0.6, 0.8, 1.0, 1.2, 1.4, 1.6, 1.8, 2.0))+
  scale_fill_brewer(palette = "Pastel1")+
  labs(x = "Tap Free Chlorine Concentration (mg/L)", 
       y = 'Stored Water Free Chlorine Concentration (mg/L)',
       color = "Assignment",
       title = "",
       caption = ""
       )+
  theme_classic() + 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1),
        plot.title = element_text(size = 2))

p_tap_vs_stored

ggsave(filename = "manuscript_tap_vs_stored_chlorine_v1.pdf", path = (paste0(github_path(), "/3_manuscript/figures")), dpi = 1080, width = 3, height = 3, units = "in", scale = 2)



#Creating figuring showing tap chlorine concentration vs stored water positive samples
                               
#Summarizing descriptive statistics for comparing across tap concentrations
rounds_summary <- rounds%>%
  filter(assignment == "Treatment")%>%
    group_by(fc_tap_pa_2) %>%
    summarise(
      "Number of Samples" = n(),
      "% Stored Samples Positive for Free Chlorine" = round((sum(fc_stored_binary == 1) / n()) * 100, 1),
      "Lower CI" = (sum(fc_stored_binary == 1) / n()) * 100 -
        (qt(0.975, n() - 1) * sd(fc_stored_binary*100)/sqrt(n())),
      "Upper CI" = (sum(fc_stored_binary == 1) / n()) * 100 +
        (qt(0.975, n() - 1) * sd(fc_stored_binary*100)/sqrt(n()))
    )%>%
  rename(fc_level = "fc_tap_pa_2")%>%
  mutate(`Lower CI` = case_when(`Lower CI` < 0 ~ 0,
                                       `Lower CI` >= 0 ~ `Lower CI`))%>%
    mutate(`Upper CI` = case_when(`Upper CI` > 100 ~ 100,
                                       `Upper CI` <= 100 ~ `Upper CI`))

#Creating plot
p_tap_vs_stored_2 <- ggplot(data = rounds_summary) + 
  geom_point(aes(x = fc_level, y = `% Stored Samples Positive for Free Chlorine`), 
           position = position_dodge(width = 0.35), size = 3) +
   geom_errorbar(aes(x = fc_level, ymin = `Lower CI`, ymax = `Upper CI`), position = position_dodge(width = 0.35),
                 width = .1) +
  scale_y_continuous(
                     limits = c(0, 100),
                     expand = c(0,0))+
  labs(x = "Free Chlorine Concentration in Tap Water (mg/L)", 
       y = "% of Stored Water Samples Positive for Free Chlorine (> 0.1 mg/L)",
       title = ""
       )+
  theme_classic() + 
  theme(axis.text.x = element_text(vjust=1))

p_tap_vs_stored_2

ggsave(filename = "manuscript_tap_vs_stored_chlorine_v2.pdf", path = (paste0(github_path(), "/3_manuscript/figures")), dpi = 1080, width = 3, height = 1.5, units = "in", scale = 2)





#Estimating average concentration after dose increase
mon_long%>%
  filter(test_date > ymd("2024-09-08"))%>%
  group_by(free_or_total, test_sample)%>%
  summarise(avg_conc = mean(chlorine_concentration),
            sd_conc = sd(chlorine_concentration))

#Estimating mean difference between paired free and total chlorine measurements
mon%>%
  filter(nearest_tap_tc >= 0.1 | farthest_tap_tc >= 0.1)%>%
  mutate(diff_taps_near = abs(nearest_tap_tc - nearest_tap_fc))%>%
  mutate(diff_taps_far = abs(farthest_tap_tc - farthest_tap_fc))%>%
  summarise(diff_tap_near_mean = mean(diff_taps_near),
            diff_tap_far_mean = mean(diff_taps_far)
            )%>%
  mean()
mon%>%
  filter(nearest_stored_tc >= 0.1 | farthest_stored_tc >= 0.1)%>%
  mutate(diff_stored_near = abs(nearest_stored_tc - nearest_stored_fc))%>%
  mutate(diff_stored_far = abs(farthest_stored_tc - farthest_stored_fc))%>%
  summarise(diff_stored_near_mean = mean(diff_stored_near),
            diff_stored_far_mean = mean(diff_stored_far)
            )%>%
  mean()  




```



