---
#title: "Code for Descriptive Stats"
#author: "Astha Vohra"
#date: "2023-10-01"
---
```{r}
# install the packages
# install.packages("googledrive", "googlesheets4", "readxl", "dplyr", "lubridate", "haven", "expss", "stargazer", "Hmisc", "ggplot2")

# install.packages("Hmisc")

# load the libraries
library(readxl) 
library(googledrive)
library(googlesheets4)
library(DBI)
library(RSQLite)
library(dplyr)
library(lubridate)
library(haven)
library(expss)
library(stargazer)
library(tidyverse)
library(Hmisc)
library(ggplot2)
library(labelled)
library(xtable)


```


```{r, setup, include=FALSE}
# setting user path
   

user_path <- function() {
  # Return a hardcoded path that depends on the current user, or the current 
  # working directory for an unrecognized user. If the path isn't readable,
  # stop.
  
  user <- Sys.info()["user"]
  
  if (user == "asthavohra") { 
    path = "/Users/asthavohra/Library/CloudStorage/Box-Box/India Water project/2_Pilot/Data/"
  } 
  else if (user=="akitokamei"){
    path = "/Users/akitokamei/Box Sync/India Water project/2_Pilot/Data/"
  } 
  else if (user == ""){
    path = ""
  } 
  else {
    warning("No path found for current user (", user, ")")
    path = getwd()
  }
  
  stopifnot(file.exists(path))
  return(path)
}

# set working directory
knitr::opts_knit$set(root.dir = user_path())

# setting github directory
github_path <- function() {
  user <- Sys.info()["user"]
  if (user == "asthavohra") {
    github = "/Users/asthavohra/Documents/GitHub/i-h2o-india/Code/2_Pilot/0_pilot logistics/"
  } 
  else if (user=="akitokamei"){
    github = "/Users/akitokamei/Library/CloudStorage/Dropbox/Mac/Documents/GitHub/i-h2o-india/Code/2_Pilot/0_pilot logistics/"
  } 
  else if (user == "") {
    github = ""
  } 
  else {
    warning("No path found for current user (", user, ")")
    github = getwd()
  }
  
  stopifnot(file.exists(github))
  return(github)
}

# setting github directory
overleaf <- function() {
  user <- Sys.info()["user"]
  if (user == "asthavohra") {
    overleaf = "/Users/asthavohra/Dropbox/Apps/Overleaf/Everything document -ILC/"
  } 
  else if (user=="akitokamei"){
    overleaf = "/Users/akitokamei/Library/CloudStorage/Dropbox/Apps/Overleaf/Everything document -ILC/"
  } 
  else if (user == "") {
    overleaf = ""
  } 
  else {
    warning("No path found for current user (", user, ")")
    overleaf = getwd()
  }
  
  stopifnot(file.exists(overleaf))
  return(overleaf)
}
```

```{r load stata clean file for descriptive stats}
df.temp <- read_dta(paste0(user_path(),"2_deidentified/1_2_Followup_cleaned.dta" ))
```

```{r assign variable labels to data frame}
temp.labels <- lapply(df.temp , var_lab)

#create a data with labels
df.label <- as.data.frame(t(as.data.frame(do.call(cbind, temp.labels)))) 
df.label<- tibble::rownames_to_column(df.label) 
df.label <- df.label %>% rename(variable = rowname, label = V1)  
auto_generated_labels <- c(df.label$variable)

#include labels given manually 
df.label.manual <- read_xlsx(paste0(user_path(),"4_other/R_code_HH_Survey_labels.xlsx"))

df.var <- as.data.frame(names(df.temp)) #List of variables in the data

# assign labels to variable that were generated
df.label.manual <- df.label.manual %>% mutate(new_var = ifelse(Variable %in% auto_generated_labels, 0,1)) %>% 
  filter(new_var == 1) %>% select(-new_var) %>% rename(variable = Variable, label = Label)

df.label <- rbind(df.label, df.label.manual)
# create a function that assigns the label to appropriate variable

```

```{r checks - full}

df.temp.consent <- df.temp[which(df.temp$R_FU_consent==1) ,]
# create variable batteries : 
#numeric vars
num_var <- names(select_if(df.temp.consent, is.numeric))

#logical vars 
log_var <- names(df.temp.consent %>%
  select_if(function(col) is.logical(col)))

#string vars
char_var <- names(df.temp.consent %>%
  select_if(function(col) is.character(col)))

# 1. Count of missing values sorted by cases higher than 5 


missing_values <- as.data.frame(sapply(df.temp.consent, function(x) sum(is.na(x))))%>% rename(   "count" = "sapply(df.temp.consent, function(x) sum(is.na(x)))") %>% filter(count != 0)
missing_values <- tibble::rownames_to_column(missing_values) 
# merge variable name to variable label using df.label
missing_values <- missing_values %>% rename(variable = rowname)
missing_values <- merge(missing_values, df.label , by = "variable")
#output to tex 



# 2. Don't Knows   
dont_know <- df.temp.consent  %>% select(num_var,log_var) 

long_data = dont_know %>% 
  pivot_longer( cols = c(num_var, log_var), names_to = "group", values_to = "response")

long_data <- long_data %>% 
  filter(response == 999) %>% group_by(group) %>% tally() %>% filter(n != 0 | !is.na(n))

long_data <- long_data %>% rename(variable = group , count_of_DK = n)
dkcount <- merge(df.label ,long_data, by = "variable") 
dkcount <- dkcount %>% select(-variable) 
#output to tex 
 stargazer(dkcount , summary=F, title= "Count of Don't Knows",float=F,rownames = F,
           covariate.labels=NULL, out=paste0(overleaf(),"Table/Table_DontKnow_HH_Survey.tex"))


# 3. Check if follow_up preload selected E.coli HH are the ones actually being tested for E.coli? 
   
  # load the preload file here.- DO LATER
 
#preload_2 <-  read_xlsx(paste0(user_path(), "Supervisor_HH_Tracker_Baseline_5 Oct 2023.xlsx"))
#output to tex 
 #stargazer::   
   
   
#4. Output all cases of others 
   
```


```{r progress table: replacement, found hh, consent, target progress}


# For target progress, follow Akito's table
submissions <- df.temp %>% select(R_FU_r_cen_village_name_str) %>%
  group_by(R_FU_r_cen_village_name_str) %>% mutate(Submission=n()) %>% ungroup()  %>% unique() %>% 
  arrange(R_FU_r_cen_village_name_str)

resp_available <- df.temp %>%  filter(R_FU_resp_available == 1 & R_FU_replacement == 0 ) %>% 
  select(R_FU_r_cen_village_name_str) %>%
  group_by(R_FU_r_cen_village_name_str) %>% mutate("OG Found" =n()) %>% ungroup()  %>% unique() %>% 
  arrange(R_FU_r_cen_village_name_str)
resp_notavailable <- df.temp %>%  filter(R_FU_resp_available != 1  ) %>% 
  select(R_FU_r_cen_village_name_str) %>%
  group_by(R_FU_r_cen_village_name_str) %>% mutate("NOT Found" =n()) %>% ungroup()  %>% unique() %>% 
  arrange(R_FU_r_cen_village_name_str)

consented <- df.temp  %>% filter(R_FU_consent == 1) %>% select(R_FU_r_cen_village_name_str) %>%
  group_by(R_FU_r_cen_village_name_str) %>% mutate(Consented=n()) %>% ungroup()  %>% unique() %>% 
  arrange(R_FU_r_cen_village_name_str)

refused <- df.temp %>% filter(R_FU_consent != 1) %>% select(R_FU_r_cen_village_name_str) %>%
  group_by(R_FU_r_cen_village_name_str) %>% mutate(Refused=n()) %>% ungroup()  %>% unique() %>% 
  arrange(R_FU_r_cen_village_name_str)

 replacements <- df.temp %>%  filter( R_FU_replacement == 1 ) %>% 
  select(R_FU_r_cen_village_name_str) %>%
  group_by(R_FU_r_cen_village_name_str) %>% mutate(Replacements=n()) %>% ungroup()  %>% unique() %>% 
  arrange(R_FU_r_cen_village_name_str)

df.progress <- left_join(submissions,resp_available)%>% left_join(resp_notavailable) %>% left_join(replacements) %>% 
  left_join(consented) %>% left_join(refused)  %>% 
  rename(Village = R_FU_r_cen_village_name_str)
df.progress[is.na(df.progress)]<-0

Total <- df.progress %>% summarise(across(where(is.numeric), ~ sum(.x, na.rm = TRUE)))
Total$Village <- "Total"
df.progress<- rbind(df.progress, Total)

#output to tex 
 stargazer(df.progress, summary=F, title= "Overall Progress: Baseline HH Survey",float=F,rownames = F,
           covariate.labels=NULL, out=paste0(overleaf(),"Table/Table_Progress_HH_Survey.tex"))

```
```{r}
#create a date variable
df.temp$date <- format(as.Date(df.temp$R_FU_starttime, "%b %d, %Y"), "%Y-%m-%d")

```


```{r survey by date and village}
#------------------------ Distribution of surveys by dates & villages ----------------------------------------#
date.plt<- df.temp %>% filter(R_FU_consent == 1) %>% 
  group_by( R_FU_r_cen_village_name_str, date) %>%
dplyr:: summarise(Date_N=n()) %>% ungroup()


#plot_date <- ggplot(date.plt %>% select(date,Date_N, village_id) %>% unique(),aes(x  =date), y = Date_N)) + geom_bar()

# CONVERT TO TABLE
tab<- spread(date.plt,key = "date", value = "Date_N")
tab <- tab %>% dplyr::mutate(total=rowSums(across(-1),na.rm = T))
tab[is.na(tab)] <- 0 
tab <- tab %>% rename(Village = R_FU_r_cen_village_name_str)
print(tab)

stargazer(tab,out= paste0(overleaf(), "Table/Table_survey_by_date_village.tex"), summary=F, float=F,rownames = F,
           covariate.labels=NULL)

```


```{r distribution of survey by enum}
#------------------------ Distribution of surveys by Enumerator, dates & villages ----------------------------------------#
date.plt<- df.temp %>% filter(R_FU_consent == 1) %>% 
  group_by( R_FU_r_cen_village_name_str,R_FU_enum_name_label,  date) %>%
dplyr:: summarise(Date_N=n()) %>% ungroup()


# CONVERT TO TABLE
tab<- spread(date.plt,key = "date", value = "Date_N")
tab <- tab %>% dplyr::mutate(total=rowSums(across(-c(1, 2)),na.rm = T))
tab[is.na(tab)] <- 0 
tab <- tab %>% rename(Village = R_FU_r_cen_village_name_str, Enumerator =R_FU_enum_name_label  )
print(tab)

stargazer(tab,out= paste0(overleaf(), "Table/Table_survey_by_enum_date_village.tex"), summary=F, float=F,rownames = F,
           covariate.labels=NULL)

```

```{r enumerator duration for each section and count of DK}

# 1. Total count of missing values by enumerators
# relevant variables which shouldnt have missings 

missing_enum <- df.temp.consent %>% select(R_FU_enum_name_label, num_var) %>%
  group_by(R_FU_enum_name_label) %>%
  summarise_all(~sum(is.na(.)))

#output to tex 
 #stargazer::
   

# 2. Duration by enumerators
   
resp_hh_location_dur_enum <- df.temp.consent %>%
  group_by(R_FU_enum_name_label) %>%
 dplyr:: summarise("Locating Respondent" = round(mean(FU_locatehh_dur_min),1)) %>% ungroup()
consent_dur_enum <- df.temp.consent %>%
  group_by(R_FU_enum_name_label) %>%
 dplyr:: summarise("Consent" = round(mean(FU_consent_dur_min),1)) %>% ungroup()
secA_dur_enum <- df.temp.consent %>% 
  group_by(R_FU_enum_name_label) %>%
 dplyr:: summarise("Sec A" = round(mean(FU_secA_dur_min),1)) %>% ungroup()
secB_dur_enum <- df.temp.consent %>% 
  group_by(R_FU_enum_name_label) %>%
 dplyr:: summarise("Sec B" = round(mean(FU_secB_dur_min),1))  %>% ungroup()
secC_dur_enum <- df.temp.consent %>% 
  group_by(R_FU_enum_name_label) %>%
 dplyr:: summarise("Sec C" = round(mean(FU_secC_dur_min),1))%>% ungroup()
secD_dur_enum <- df.temp.consent %>% 
  group_by(R_FU_enum_name_label) %>%
 dplyr:: summarise("Sec D" = round(mean(FU_secD_dur_min),1))  %>% ungroup()
total_dur_enum <- df.temp.consent %>% 
  group_by(R_FU_enum_name_label) %>%
 dplyr:: summarise("Overall" = round(mean(R_FU_duration_end/60),1))  %>% ungroup()

df.duration.enum <- left_join(resp_hh_location_dur_enum,consent_dur_enum) %>% left_join(secA_dur_enum) %>% 
 left_join(secB_dur_enum) %>% 
   left_join(secC_dur_enum) %>% 
   left_join(secC_dur_enum) %>%
  left_join(secD_dur_enum) %>%
   left_join(total_dur_enum) 
df.duration.enum <- df.duration.enum %>% rename(Enumerator = R_FU_enum_name_label )
star.out <- stargazer(df.duration.enum, summary=F, title= "Duraction by section Baseline HH Survey by enumerator",float=F,rownames = F,covariate.labels=NULL)
star.out <- sub("cccccccc", "lccccccc", star.out)
starpolishr::star_tex_write(star.out,  file =paste0(overleaf(),"Table/Table_Duration_enum_HH_Survey.tex"))


# Duration of water quality testing by type of test
secE_cl_dur_enum <- df.temp.consent %>%  filter(R_FU_water_qual_test == 1) %>% 
  mutate(FU_secE_dur_min  = ifelse(FU_secE_dur_min<0 , NA, FU_secE_dur_min)) %>% 
  group_by(R_FU_enum_name_label) %>%
 dplyr:: summarise("Chlorine Testing"= round(mean(FU_secE_dur_min, na.rm = T),1))  %>% ungroup()

secE_both_dur_enum <- df.temp.consent %>%  filter(R_FU_water_qual_test == 2) %>% 
  mutate(FU_secE_dur_min  = ifelse(FU_secE_dur_min<0 , NA, FU_secE_dur_min)) %>% 
  group_by(R_FU_enum_name_label) %>%
 dplyr:: summarise("Both Testing"= round(mean(FU_secE_dur_min, na.rm = T),1))  %>% ungroup()

df.duration.wq.enum <- left_join(secE_cl_dur_enum,secE_both_dur_enum) 
df.duration.wq.enum <- df.duration.wq.enum %>% rename(Enumerator = R_FU_enum_name_label )
star.out <- stargazer(df.duration.wq.enum, summary=F, title= "Duraction by WQ Test Baseline HH Survey by enumerator",float=F,rownames = F,covariate.labels=NULL)
star.out <- sub("ccc", "lcc", star.out)
starpolishr::star_tex_write(star.out,  file =paste0(overleaf(),"Table/Table_Duration_WQ_enum_HH_Survey.tex"))

#3. Count of Dont Know by enumerators 

df.dk.enum <- df.temp.consent %>%
  group_by(R_FU_enum_name_label) %>%
  summarise_all(~sum(. == 999)) %>% 
  transmute(R_FU_enum_name_label, sum_dk = rowSums(.[-1], na.rm = T)) %>% 
  rename(Enumerator = R_FU_enum_name_label, "Count of DK" = sum_dk)

stargazer(df.dk.enum, summary=F, title= "Count of DK by enumerator",float=F,rownames = F,
           covariate.labels=NULL, out=paste0(overleaf(),"Table/Table_DK_enum_HH_Survey.tex"))


```

```{r descriptive stats - duration}


resp_hh_location_dur <- df.temp.consent %>% filter(FU_locatehh_dur_min > 0) %>%
 dplyr:: summarise(mean = round(mean(FU_locatehh_dur_min),1), min = round(min(FU_locatehh_dur_min),1), max = round(max(FU_locatehh_dur_min),1))  %>%
  mutate(variable = "Locating HH")
consent_dur <- df.temp.consent %>%  filter(FU_consent_dur_min > 0) %>%
 dplyr:: summarise(mean = round(mean(FU_consent_dur_min),1), min = round(min(FU_consent_dur_min),1), max = round(max(FU_consent_dur_min),1) ) %>%
  mutate(variable = "Consent")
secA_dur <- df.temp.consent %>% filter(FU_secA_dur_min > 0) %>%
 dplyr:: summarise(mean = round(mean(FU_secA_dur_min),1), min = round(min(FU_secA_dur_min),1), max = round(max(FU_secA_dur_min),1) ) %>%
  mutate(variable = "Sec A: WASH Access")
secB_dur <- df.temp.consent %>% filter(FU_secB_dur_min > 0) %>%
 dplyr:: summarise(mean = round(mean(FU_secB_dur_min),1), min = round(min(FU_secB_dur_min),1), max = round(max(FU_secB_dur_min),1) ) %>%
  mutate(variable = "Sec B: Government Tap")
secC_dur <- df.temp.consent %>% filter(FU_secC_dur_min > 0) %>%
 dplyr:: summarise(mean = round(mean(FU_secC_dur_min),1), min = round(min(FU_secC_dur_min),1), max = round(max(FU_secC_dur_min),1) ) %>%
  mutate(variable = "Sec C: Chlorination Perceptions")
secD_dur <- df.temp.consent %>% filter(FU_secD_dur_min > 0) %>%
 dplyr:: summarise(mean = round(mean(FU_secD_dur_min),1), min = round(min(FU_secD_dur_min),1), max = round(max(FU_secD_dur_min),1) ) %>%
  mutate(variable = "Sec D: Burden")

overall_mean <- df.temp.consent %>% filter(R_FU_duration_end > 0) %>%
 dplyr:: summarise(mean = round(mean(R_FU_duration_end/60),1), min = round(min(R_FU_duration_end/60),1), max = round(max(R_FU_duration_end/60),1) ) %>%
  mutate(variable = "Overall")

df.duration <- bind_rows(resp_hh_location_dur,consent_dur, secA_dur,secB_dur, secC_dur, secD_dur, overall_mean)

df.duration <- df.duration %>% select(variable , mean, min, max) %>% mutate(mean = round(mean, 3), min = round(min, 3), max = round(max, 3)) %>%   rename("Duration\ Section" = variable, "Mean \ (in mins)" = mean, "Min \ (in mins)" = min, "Max \ (in mins)" = max ) 
stargazer(df.duration, summary=F, title= "Duraction by section Baseline HH Survey",float=F,rownames = F,
           covariate.labels=NULL, out=paste0(overleaf(),"Table/Table_Duration_HH_Survey.tex"))



# Section on Water Quality Testing, separate duration by whether sample was collected or not? 

secE_dur_chlorine <- df.temp.consent %>% filter(R_FU_water_qual_test == 1) %>% 
  mutate(FU_secE_dur_min  = ifelse(FU_secE_dur_min<0 , NA, FU_secE_dur_min)) %>% 
 dplyr:: summarise(mean = round(mean(FU_secE_dur_min, na.rm = T),1), min = round(min(FU_secE_dur_min,  na.rm = T),1), max = round(max(FU_secE_dur_min,  na.rm = T),1) ) %>%
  mutate(variable = "Chlorine Testing")
secE_dur_both <- df.temp.consent %>% filter(R_FU_water_qual_test == 2) %>% 
  mutate(FU_secE_dur_min  = ifelse(FU_secE_dur_min<0 , NA, FU_secE_dur_min)) %>% 
 dplyr:: summarise(mean = round(mean(FU_secE_dur_min, na.rm = T),1), min = round(min(FU_secE_dur_min,  na.rm = T),1), max = round(max(FU_secE_dur_min,  na.rm = T),1) ) %>%
  mutate(variable = "Both Testing")

df.duration.wq <- bind_rows(secE_dur_chlorine,secE_dur_both)

df.duration.wq <- df.duration.wq %>% select(variable , mean, min, max) %>% mutate(mean = round(mean, 3), min = round(min, 3), max = round(max, 3)) %>%   rename("Duration\ Section" = variable, "Mean \ (in mins)" = mean, "Min \ (in mins)" = min, "Max \ (in mins)" = max ) 
stargazer(df.duration.wq, summary=F, title= "Duraction for Water Quality Test -  Baseline HH Survey",float=F,rownames = F,
           covariate.labels=NULL, out=paste0(overleaf(),"Table/Table_Duration_WQ_HH_Survey.tex"))

```

```{r descriptive stats - water quality test}

bl <- df.temp.consent
 
###Displaying chlorine test data for each village
#Arranging data so chlorine test data is in one column
chlorine <- bl%>%
  pivot_longer(cols = c(R_FU_fc_tap, R_FU_fc_stored, R_FU_tc_tap, R_FU_tc_stored), values_to = "chlorine_concentration", names_to = "chlorine_test_type")
#Removing NAs from no respondent being available
chlorine <- chlorine%>%
  filter(is.na(chlorine_concentration) == FALSE)
p1 <- ggplot(data =chlorine) + geom_point(aes(x = chlorine_test_type, y = chlorine_concentration), size = 3) +
  facet_wrap(~ R_FU_r_cen_village_name_str) +
  labs(x = "Chlorine Test", y = "Chlorine Concentration (mg/L)") +
  theme_bw() + scale_x_discrete(labels=c("FCl-Stored" , "FCl-Running", "TCl-Stored", "TCl-Running"))+
  theme(axis.title.y = element_text(size = 32), axis.title.x = element_text(size = 32), 
  axis.text.x =  element_text(size = 18, face="bold"), axis.text.y =  element_text(size = 30, face="bold"), 
  strip.text = element_text(size = 40)) 


ggplot2::ggsave( paste0(overleaf(),"Figure/Chlorine-concentration-village.png"), p1,  width = 21, height= 13,dpi=200)

#Selecting for data that are > 0.10 mg/L
chlorine_c <- chlorine%>%
  filter(chlorine_concentration > 0.10)%>% 
  dplyr::select(unique_id_num, R_FU_enum_name_label, R_FU_r_cen_village_name_str, chlorine_test_type, chlorine_concentration)
chlorine_c <- chlorine_c %>%   
  mutate(chlorine_test_type = ifelse(chlorine_test_type == "R_FU_tc_tap", "TCl-Running",
                                     ifelse(chlorine_test_type == "R_FU_fc_tap", "FCl-Running",
                                            ifelse(chlorine_test_type == "R_FU_tc_stored", "TCl-Stored", 
                                                   ifelse(chlorine_test_type == "R_FU_fc_stored", "FCl-Stored", NA))))) %>% 
  mutate(chlorine_concentration  = round(chlorine_concentration, 3)) %>% 
  rename("Unique HH ID" =unique_id_num , Enumerator = R_FU_enum_name_label , 
         Village = R_FU_r_cen_village_name_str, "Test Type" = chlorine_test_type , 
         Concentration =  chlorine_concentration ) 

#Frequency of cases above 0.1 by enumerator
chlorine_check <- chlorine%>%
  filter(chlorine_concentration > 0.10)%>% 
  dplyr::select(R_FU_enum_name_label) %>% 
  group_by(R_FU_enum_name_label) %>% 
  mutate(Case_above_0.1 = n()) %>% ungroup()  %>% unique() 
stargazer(chlorine_check, summary=F, title= "Count of Chlorine reading greater than 0.10",float=F,rownames = F,
           covariate.labels=NULL, out=paste0(overleaf(),"Table/Table_Chlorine_high_HH_Survey.tex"))


# Displaying chlorine test data for each village
# Arranging data so chlorine test data is in one column
chlorine <- bl%>%
  pivot_longer(cols = c(R_FU_fc_tap, R_FU_fc_stored, R_FU_tc_tap, R_FU_tc_stored), values_to = "chlorine_concentration", names_to = "chlorine_test_type")
#Removing NAs from no respondent being available
chlorine <- chlorine%>%
  filter(is.na(chlorine_concentration) == FALSE)
p2 <- ggplot(data =chlorine) + geom_point(aes(x = chlorine_test_type, y = chlorine_concentration), size = 5) +
  labs(x = "Chlorine Test", y = "Chlorine Concentration (mg/L)") +
  theme_bw() +  scale_x_discrete(labels=c("FCl - Stored" , "FCl - Running", "TCl - Stored", "TCl - Running")) +
  theme(axis.title.y = element_text(size = 32), axis.title.x = element_text(size = 32), 
  axis.text.x =  element_text(size = 32, face="bold"), axis.text.y =  element_text(size = 30, face="bold")) 


ggplot2::ggsave( paste0(overleaf(),"Figure/Chlorine-concentration.png"), p2,  width = 22, height= 15,dpi=200)




```


```{r descriptive stats - sample collection}

bl <- df.temp.consent
 
###Displaying chlorine test data for each village
#Arranging data so chlorine test data is in one column
df.sample <- bl%>%
  pivot_longer(cols = c("R_FU_wq_stored_bag", "R_FU_wq_running_bag"), values_to = "yes_no", names_to = "sample_type")

#Removing NAs from no respondent being available
df.sample <- df.sample%>%
  filter(is.na(yes_no) == FALSE) %>% dplyr::select(R_FU_enum_name_label, R_FU_r_cen_village_name_str, sample_type, yes_no)

#Frequency of sample collection
df.count.stored <- df.sample%>% filter(sample_type == "R_FU_wq_stored_bag") %>%
  group_by(R_FU_r_cen_village_name_str, sample_type) %>% 
  mutate(Count_of_Sample = n()) %>% ungroup()  %>% 
  dplyr::select(R_FU_r_cen_village_name_str, Count_of_Sample) %>% 
  rename(Village = R_FU_r_cen_village_name_str,  "Count-Stored Water" = Count_of_Sample ) %>% 
  unique()
df.count.running <- df.sample%>% filter(sample_type == "R_FU_wq_running_bag") %>%
  group_by(R_FU_r_cen_village_name_str, sample_type) %>% 
  mutate(Count_of_Sample = n()) %>% ungroup()  %>% 
  dplyr::select(R_FU_r_cen_village_name_str, Count_of_Sample) %>% 
  rename(Village = R_FU_r_cen_village_name_str, "Count-Running Water" = Count_of_Sample ) %>% 
  unique()

df.count <- left_join(df.count.stored, df.count.running)
stargazer(df.count, summary=F, title= "Count of Sample collection",float=F,rownames = F,
           covariate.labels=NULL, out=paste0(overleaf(),"Table/Table_sample_HH_Survey.tex"))


#Frequency of sample collection by enumerator
df.sample.stored.enum <- df.sample%>% filter(sample_type == "R_FU_wq_stored_bag") %>% 
  group_by(R_FU_enum_name_label, sample_type) %>% 
  mutate(Count_of_Sample = n()) %>% ungroup()  %>% 
  dplyr::select(R_FU_enum_name_label, Count_of_Sample) %>% 
  rename(Enumerator = R_FU_enum_name_label, "Count-Stored Water" = Count_of_Sample ) %>% 
  unique() 

df.sample.running.enum <- df.sample%>% filter(sample_type == "R_FU_wq_running_bag") %>% 
  group_by(R_FU_enum_name_label, sample_type) %>% 
  mutate(Count_of_Sample = n()) %>% ungroup()  %>%
  dplyr::select(R_FU_enum_name_label, Count_of_Sample) %>% 
  rename(Enumerator = R_FU_enum_name_label, "Count-Running Water" = Count_of_Sample ) %>% 
  unique()
df.sample.enum <- left_join(df.sample.stored.enum, df.sample.running.enum)
stargazer(df.sample.enum, summary=F, title= "Count of Sample collection by enum",float=F,rownames = F,
           covariate.labels=NULL, out=paste0(overleaf(),"Table/Table_sample_enum_HH_Survey.tex"))





```


```{r descriptive sec A wash access}
df.wash <- df.temp.consent %>% select(R_FU_water_source_prim, R_FU_water_sec_yn,  R_FU_quant, R_FU_water_treat, R_FU_water_stored)
#assign labels for each

  var_lab(df.wash$R_FU_water_source_prim) = "Primary drinking water source?"
val_lab(df.wash$R_FU_water_source_prim) = num_lab("
            1 Government provided household Taps (supply paani)
            2 Government provided community standpipe    
            3 Gram Panchayat/Other Community Standpipe (e.g. solar pump, PVC tank)
            4	Manual handpump
            5	Covered dug well
            6	Directly fetched by surface water
            7	Uncovered dug well
            8	Private Surface well    
            ")

var_lab(df.wash$R_FU_water_sec_yn) = "Any other source of drinking water?"
val_lab(df.wash$R_FU_water_sec_yn) = num_lab("
            1 Yes
            2 No
            999 Don't Know
            ")
var_lab(df.wash$R_FU_quant) = "How much drinking water came from primary water source?"
val_lab(df.wash$R_FU_quant) = num_lab("
            1	All of it
            2	Most of it
            3	Half of it
            4	Little of it
            5	None of it
            ")
var_lab(df.wash$R_FU_water_treat) = "Is primary drinking water source treated?"
val_lab(df.wash$R_FU_water_treat) = num_lab("
            1 Yes
            2 No
            999 Don't Know
            ")

var_lab(df.wash$R_FU_water_stored) = "Is the water stored currently in the house treated?"
val_lab(df.wash$R_FU_water_stored) = num_lab("
            1 Yes
            2 No
            999 Don't Know
            ")

df.append <- as.data.frame(matrix(NA, ncol = 3)) 
df.append_var <- as.data.frame(matrix(NA, ncol = 3))  

colnames(df.append) <- c('Var1', 'Freq', 'Prop')
colnames(df.append_var) <- c('Var1', 'Freq', 'Prop')

var_names <- names(df.wash)
for (i in var_names){
     
     df.append_var$Var1 <- i
    df.append <-  rbind(df.append,df.append_var)
     freq_tab <- as.data.frame(table(df.wash[,i]))
     prop_tab <- as.data.frame(prop(table(df.wash[,i])))
     prop_tab <- prop_tab %>% rename(Prop = Freq)
     freq_tab[,1] <- as.character(freq_tab[,1])
     
     df.stat <- merge(freq_tab, prop_tab) 
     colnames(df.stat) <- c("Var1", "Freq", "Prop")
    
     df.append <- rbind(df.append, df.stat)
}
df.append <- df.append %>% mutate(Var1 = ifelse(Var1 == "0", "No", Var1)) %>% 
  mutate(Var1 = ifelse(Var1 == "R_FU_water_source_prim", "Primary drinking water source?", 
                       ifelse(Var1 == "R_FU_water_sec_yn","Any other source of drinking water?", 
                              ifelse(Var1 == "R_FU_quant", "How much drinking water came from primary water source?", 
                                     ifelse(Var1 == "R_FU_water_treat", "Is primary drinking water source treated?", 
                                            ifelse(Var1 == "R_FU_water_stored", 
                                                   "Is the water stored currently in the house treated?", Var1)))))) %>%
  rename(Question = Var1) %>% mutate(Prop = round(Prop, 2))

star.out <- stargazer(df.append, summary=F, title= "WASH Section Summary",float=F,rownames = F,
           covariate.labels=NULL)

star.out <- sub(" ccc"," l{5cm}c{2cm}c{2cm}c{2cm}", star.out) 

starpolishr::star_tex_write(star.out,  file =paste0(overleaf(),"Table/Table_Wash_HH_Survey.tex"))
 


#what treatment? 
     
df.treat <- df.temp.consent %>% filter(R_FU_water_treat == 1| R_FU_water_stored == 1) %>% select(R_FU_water_treat,R_FU_water_stored, R_FU_water_treat_type)
df.treat$R_FU_water_treat_type <- ordered(df.treat$R_FU_water_treat_type,
                                          levels = c(1,2,3,4, -77),
                                          labels = c("Filter the water through a cloth or sieve", 
                                                     "Let the water stand for some time ", 
                                                     "Boil the water", 
                                                     "Add chlorine/ bleaching powder", 
                                                     "Other"))


freq_tab <- table(df.treat$R_FU_water_treat_type)
     prop_tab <- as.data.frame(prop(freq_tab))
     prop_tab <- prop_tab %>% rename(Prop = Freq)
     df.stat <- merge(freq_tab, prop_tab) 

df.stat$Prop <- round(proportions(df.stat$Freq), 2)
df.stat <- df.stat %>% rename("Type of treatment" = Var1)
stargazer(df.stat, summary=F, title= "WASH Section Summary",float=F,rownames = F,
           covariate.labels=NULL, out=paste0(overleaf(),"Table/Table_treat_HH_Survey.tex"))
         
```

```{r for archi - give hh_ids and name of enums who report diff primary water source than government taps}
df.wash.not.prim <- df.temp.consent %>% filter(R_FU_water_source_prim != 1) %>% 
  select(R_FU_enum_name_label, R_FU_r_cen_village_name_str, unique_id_num, R_FU_water_source_prim )  %>%
  rename( Enumerator = R_FU_enum_name_label, Village  = R_FU_r_cen_village_name_str, HH_ID = unique_id_num, 
          Primary_Water_Source = R_FU_water_source_prim) %>% 
  mutate(Primary_Water_Source = ifelse(Primary_Water_Source == 2,"Government provided community standpipe",
                                       ifelse(Primary_Water_Source == 3, "Gram Panchayat/Other Community Standpipe", 
                                              ifelse(Primary_Water_Source == 4,"Manual handpump", 
                                                     ifelse(Primary_Water_Source == 5, "Covered dug well", 
                                                            ifelse(Primary_Water_Source == 6, 
                                                                   "Directly fetched by surface water", 
                                                                   ifelse(Primary_Water_Source == 7, 
                                                                          "Uncovered dug well", 
                                                                          ifelse(Primary_Water_Source == 8, 
                                                                                 "Private Surface well", 
                                                                                 Primary_Water_Source))))))))


star.out <- stargazer(df.wash.not.prim, summary=F, title= "",float=F,rownames = F,
           covariate.labels=NULL)
star.out <- sub(" cccc"," lccc", star.out) 
starpolishr::star_tex_write(star.out,  file =paste0(overleaf(),"Table/Table_NOT_Govt_tap_HH_Survey.tex"))

```


```{r descriptive sec B tap }
df.tap<- df.temp.consent %>% select(R_FU_tap_supply_freq, R_FU_tap_function, R_FU_tap_use_future)
#assign labels for each

  var_lab(df.tap$R_FU_tap_supply_freq) = "How often is water supplied from government taps?"
  val_lab(df.tap$R_FU_tap_supply_freq) = num_lab("
            1	Daily
            2	Few days in a week
            3	Once a week 
            4	Few times in a month
            5	Once a month
            6	No fixed schedule
            -77	Other
            999	Don’t know
            -98	Refused to answer    
            ")
 var_lab(df.tap$R_FU_tap_function) = "In the last two weeks, have you not been able to collect water from taps?"
  val_lab(df.tap$R_FU_tap_function) = num_lab("
           1 Yes
           2 No
           999 Don't Know    
            ")
  
  
  var_lab(df.tap$R_FU_tap_use_future) = "How likely to use/continue the government tap for drinking?"
  val_lab(df.tap$R_FU_tap_use_future) = num_lab("
           1	Very likely
           2	Somewhat likely
           3	Neither likely nor unlikely
           4	Somewhat Unlikely
           5	Very unlikely
            ") 
 
  
df.append <- as.data.frame(matrix(NA, ncol = 3)) 
df.append_var <- as.data.frame(matrix(NA, ncol = 3))  

colnames(df.append) <- c('Var1', 'Freq', 'Prop')
colnames(df.append_var) <- c('Var1', 'Freq', 'Prop')

var_names <- names(df.tap)
for (i in var_names){
     
     df.append_var$Var1 <- i
    df.append <-  rbind(df.append,df.append_var)
     freq_tab <- as.data.frame(table(df.tap[,i]))
     prop_tab <- as.data.frame(prop(table(df.tap[,i])))
     prop_tab <- prop_tab %>% rename(Prop = Freq)
     freq_tab[,1] <- as.character(freq_tab[,1])
     
     df.stat <- merge(freq_tab, prop_tab) 
     colnames(df.stat) <- c("Var1", "Freq", "Prop")
    
     df.append <- rbind(df.append, df.stat)
}
df.append <- df.append %>% mutate(Var1 = ifelse(Var1 == "0", "No", Var1)) %>% 
  mutate(Var1 = ifelse(Var1 == "R_FU_tap_supply_freq", "How often is water supplied from government taps?", 
                       ifelse(Var1 == "R_FU_tap_function",
                              "In the last two weeks, have you not been able to collect water from taps?", 
                                     ifelse(Var1 == "R_FU_tap_use_future", 
                                            "How likely to use/continue the government tap for drinking?", 
                                        Var1)))) %>%
  rename(Question = Var1) %>% mutate(Prop = round(Prop, 2))




star.out <- stargazer(df.append, summary=F, title= "Tap Section Summary",float=F,rownames = F,
           covariate.labels=NULL)
star.out <- sub(" ccc"," l{5cm}c{2cm}c{2cm}c{2cm}", star.out) 

starpolishr::star_tex_write(star.out,  file =paste0(overleaf(),"Table/Table_Tap_HH_Survey.tex"))
 

```


```{r descriptive sec C chlorine perceptions }
df.cl<- df.temp.consent %>% select(R_FU_tap_taste_satisfied, R_FU_tap_taste_desc,  R_FU_tap_smell, R_FU_tap_color, 
                                   R_FU_tap_trust)
#assign labels for each
 var_lab(df.cl$R_FU_tap_taste_satisfied) = "How satisfied are you with the taste of water from government taps?"
  val_lab(df.cl$R_FU_tap_taste_satisfied) = num_lab("
            1	Very satisfied
            2	Satisfied
            3	Neither satisfied nor dissatisfied
            4	Dissatisfied
            5	Very dissatisfied
            999	Don’t know    
            ")
 var_lab(df.cl$R_FU_tap_taste_desc) = "Describe the taste of water from government taps"
  val_lab(df.cl$R_FU_tap_taste_desc) = num_lab("
            1	Good
            2	Medicine or chemical
            3	Metal
            4	Salty
            5	Bleach/chlorine
            999	Don’t know
            -77	Other    
            ") 
var_lab(df.cl$R_FU_tap_smell) = "Describe the smell of water from government taps"
  val_lab(df.cl$R_FU_tap_smell) = num_lab("
            1	Good
            2	Medicine or chemical
            3	Metal
            4	Salty
            5	Bleach/chlorine
            999	Don’t know
            -77	Other    
            ")   
var_lab(df.cl$R_FU_tap_color) = "Describe the color of water from government taps"
  val_lab(df.cl$R_FU_tap_color) = num_lab("
            1	No problems with the color or look
            2	Muddy/ sandy water
            3	Yellow-ish or reddish water (from iron)
            999	Don’t know
            -77	Other    
            ")   
  var_lab(df.cl$R_FU_tap_trust) = "How confident are you in the water from government taps?"
  val_lab(df.cl$R_FU_tap_trust) = num_lab("
            1	Very confident
            2	Somewhat confident
            3	Neither confident or not confident
            4	Somewhat not confident
            5	Not confident at all    
            ")   
  


df.append <- as.data.frame(matrix(NA, ncol = 3)) 
df.append_var <- as.data.frame(matrix(NA, ncol = 3))  

colnames(df.append) <- c('Var1', 'Freq', 'Prop')
colnames(df.append_var) <- c('Var1', 'Freq', 'Prop')

var_names <- names(df.cl)
for (i in var_names){
     
     df.append_var$Var1 <- i
    df.append <-  rbind(df.append,df.append_var)
     freq_tab <- as.data.frame(table(df.cl[,i]))
     prop_tab <- as.data.frame(prop(table(df.cl[,i])))
     prop_tab <- prop_tab %>% rename(Prop = Freq)
     freq_tab[,1] <- as.character(freq_tab[,1])
     
     df.stat <- merge(freq_tab, prop_tab) 
     colnames(df.stat) <- c("Var1", "Freq", "Prop")
    
     df.append <- rbind(df.append, df.stat)
}
df.append <- df.append %>% mutate(Var1 = ifelse(Var1 == "0", "No", Var1)) %>% 
  mutate(Var1 = ifelse(Var1 == "R_FU_tap_taste_satisfied", "How satisfied are you with the taste of water from government taps?", 
                       ifelse(Var1 == "R_FU_tap_taste_desc",
                              "Describe the taste of water from government taps", 
                                     ifelse(Var1 == "R_FU_tap_smell", 
                                            "Describe the smell of water from government taps",
                                            ifelse(Var1 == "R_FU_tap_color",
                                                   "Describe the color of water from government taps", 
                                                   ifelse(Var1 == "R_FU_tap_trust",
                                                   "How confident are you in the water from government taps?", 
                                                   Var1)))))) %>%
  rename(Question = Var1) %>% mutate(Prop = round(Prop, 2))



star.out <- stargazer(df.append, summary=F, title= "Chlorine Perceptions Section Summary",float=F,rownames = F,
           covariate.labels=NULL)
star.out <- sub(" ccc"," l{5cm}c{2cm}c{2cm}c{2cm}c{2cm}c{2cm}", star.out) 

starpolishr::star_tex_write(star.out,  file =paste0(overleaf(),"Table/Table_Chlorine_HH_Survey.tex"))
 

#Create a table on chlorine experience with treatment and drinking chlorinated water:

df.cl.exp<- df.temp.consent %>% select( R_FU_chlorine_yesno, R_FU_chlorine_drank_yesno )
var_lab(df.cl.exp$R_FU_chlorine_yesno) = "Have you ever used chlorine as a method for treating drinking water?"
  val_lab(df.cl.exp$R_FU_chlorine_yesno) = num_lab("
           1 Yes
           2 No
           999 Don't Know     
            ")

var_lab(df.cl.exp$R_FU_chlorine_drank_yesno) = "Have you ever drunk water treated with chlorine?"
  val_lab(df.cl.exp$R_FU_chlorine_drank_yesno) = num_lab("
           1 Yes
           2 No
           999 Don't Know     
            ")
  
df.exp <- as.data.frame(matrix(NA, ncol = 3)) 
df.exp_var <- as.data.frame(matrix(NA, ncol = 3))  

colnames(df.exp) <- c('Var1', 'Freq', 'Prop')
colnames(df.exp_var) <- c('Var1', 'Freq', 'Prop')

var_names <- names(df.cl.exp)
for (i in var_names){
     
     df.exp_var$Var1 <- i
    df.exp <-  rbind(df.exp,df.exp_var)
     freq_tab <- as.data.frame(table(df.cl.exp[,i]))
     prop_tab <- as.data.frame(prop(table(df.cl.exp[,i])))
     prop_tab <- prop_tab %>% rename(Prop = Freq)
     freq_tab[,1] <- as.character(freq_tab[,1])
     
     df.stat.exp <- merge(freq_tab, prop_tab) 
     colnames(df.stat.exp) <- c("Var1", "Freq", "Prop")
    
     df.exp <- rbind(df.exp, df.stat.exp)
}
df.exp <- df.exp %>% mutate(Var1 = ifelse(Var1 == "0", "No", Var1)) %>% 
  mutate(Var1 = ifelse(Var1 == "R_FU_chlorine_yesno", "Have you ever used chlorine as a method for treating drinking water?", 
                       ifelse(Var1 == "R_FU_chlorine_drank_yesno",
                              "Have you ever drunk water treated with chlorine?", 
                                                   Var1))) %>%
  rename(Question = Var1) %>% mutate(Prop = round(Prop, 2))


star.out <- stargazer(df.exp, summary=F, title= "Chlorine Experience Summary",float=F,rownames = F,
           covariate.labels=NULL)
star.out <- sub(" ccc"," l{5cm}c{2cm}c{2cm}", star.out) 

starpolishr::star_tex_write(star.out,  file =paste0(overleaf(),"Table/Table_Chlorine_Exp_HH_Survey.tex"))
 
```


```{r descriptive sec D burden of water treat }
#df.burden<- df.temp.consent %>% select(R_FU_water_source_prim, R_FU_water_sec_yn,  R_FU_quant, R_FU_water_treat, R_FU_water_stored)
#assign labels for each


#stargazer(df.append, summary=F, title= "Tap Section Summary",float=F,rownames = F,
          # covariate.labels=NULL, out=paste0(overleaf(),"Table/Table_Wash_HH_Survey.tex"))

```

