---
theme: cerulean
output: pdf_document
---

```{r setup, echo = FALSE, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, include = FALSE)
```



```{r package loading}


library(rsurveycto)
library(httr)
library(lubridate)
library(quantitray)
library(sjmisc)
library(knitr)
library(kableExtra)
library(googlesheets4)
library(googledrive)
library(readxl)
library(experiment)
library(tidyverse)


```



```{r data loading}

#From Google Drive -- Excel
# drive_auth()
# files <- drive_find(n_max = 1, pattern = "India ILC_Pilot_Household Tracking.xlsx", type = "spreadsheet")
# hh <- drive_download(files)%>%
#   read_excel()

#from Google Drive -- Google Sheets
#Pulls raw survey data
#gs4_auth()
#sheet_url <- "https://docs.google.com/spreadsheets/d/1pQISSkcqa1VQYoaWnfXaXMHUWYs4nhqYCcxviQqUn3Y/edit#gid=0"
#hh <- read_sheet(sheet_url, sheet = 3)
#hh <- gs4_find(sheet_url)


#from Google Drive -- Google Sheets
#Pulls HHs randomly selected for follow-up
#OLD Method -- no longer using Google Drive but keeping for reference
#gs4_auth()
#sheet_url <- "https://docs.google.com/spreadsheets/d/1pQISSkcqa1VQYoaWnfXaXMHUWYs4nhqYCcxviQqUn3Y/edit#gid=0"
#hh_randomization <- read_sheet(sheet_url, sheet = 1)%>%
#  dplyr::select(household_ID, 
#                selected_for_baseline_survey,
#                selected_for_baseline_WQ_sample,
#                selected_for_follow_up_1,
#                selected_for_follow_up_1_WQ_sample,
#                selected_for_follow_up_2,
#                selected_for_follow_up_2_WQ_sample,
#                selected_for_follow_up_3,
#                selected_for_follow_up_3_WQ_sample)
#hh <- gs4_find(sheet_url)


#Selecting file path to Household Tracking Excel Sheet
#Jeremy's file path
sheet_path <- "C:/Users/jerem/Box/India Water project/2_Pilot/Data/1_raw/0_field logistics/1_raw/India ILC_Pilot_Household Tracking_raw.csv" 
#Reading in raw data
hh <- read_csv(sheet_path)




#Jeremy's file path
sheet_path <- "C:/Users/jerem/Box/India Water project/2_Pilot/Data/1_raw/0_field logistics/3_household tracking/India ILC_Pilot_Household Tracking_full.csv" 
#Reading in data for HHs that were randomly selected
#Data are located in Box at: Box\India Water project\2_Pilot\Data\1_raw\0_field logistics
hh_randomization <- read_csv(sheet_path)%>%
 dplyr::select(household_ID,
               selected_for_baseline_survey,
               selected_for_baseline_WQ_sample,
               selected_for_follow_up_1,
               selected_for_follow_up_1_WQ_sample,
               selected_for_follow_up_2,
               selected_for_follow_up_2_WQ_sample,
               selected_for_follow_up_3,
               selected_for_follow_up_3_WQ_sample)





```

```{r selecting village(s) of interest and formatting data}

#Selecting which villages to create an information printout for
ID_selected <- c(1001,1002)
#Important to change this for the village you want information on!
#Could adapt this code to prompt the user for an ID list instead

#Selecting key information from raw data
hh <- hh%>%
  filter(village_ID %in% ID_selected)%>%
  dplyr::select(household_ID, district, block, village, village_ID,
                participant_name, phone, second_name, backup_phone, elder_male_name, address, landmark)%>%
  mutate(visited = "  ")
# preg_moth, child_under5) # Will update when survey is finished and variable names are coded



```


```{r Baseline print out, include = TRUE}

#Selecting for HHs that were randomly selected for baseline survey
hh_printout <- hh_randomization%>%
  filter(selected_for_baseline_survey == 1)%>%
  dplyr::select(household_ID)

#Joining HH raw data to these HH IDs
hh_printout <- left_join(hh_printout, hh, by = "household_ID")

#Creating kable printout of key information for enumerators
#Need to update variable names to Odia translation
column_names <- hh_printout%>% 
  names() %>% 
  str_replace_all( "_", "\n")

hh_printout%>%
  kbl(
    align = "l",
    #col.names = linebreak(column_names, align = "l"),
    #escape = FALSE
  )%>%
  kable_styling(position = "center",
                bootstrap_options = "striped",
                latex_options = c("scale_down", "HOLD_position"))%>%
  add_header_above(c("Baseline Survey HH Information " = 13)) %>%
  row_spec(0, bold = TRUE, color = "black", background = "white") %>%
  column_spec(1, bold = TRUE)%>%
  column_spec(2, width = "75px")%>%
  landscape(margin = NULL)


```


