---
title: "Upload_Google_Drive"
author: "Astha Vohra"
date: "2023-09-24"
output: html_document
---
```{r}
# install the packages
#install.packages("googledrive", "googlesheets4", "readxl")

# load the libraries
library(readxl) 
library(googledrive)
library(googlesheets4)
library(DBI)
library(RSQLite)


```


```{r, setup, include=FALSE}
# setting user path
   

user_path <- function() {
  # Return a hardcoded path that depends on the current user, or the current 
  # working directory for an unrecognized user. If the path isn't readable,
  # stop.
  
  user <- Sys.info()["user"]
  
  if (user == "asthavohra") { 
    path = "/Users/asthavohra/Library/CloudStorage/Box-Box/India Water project/2_Pilot/Data/"
  } 
  else if (user==""){
    path = "/Users/asthavohra/Library/CloudStorage/Box-Box/India Water project/2_Pilot/Data/"
  } 
  else if (user == ""){
    path = ""
  } 
  else {
    warning("No path found for current user (", user, ")")
    path = getwd()
  }
  
  stopifnot(file.exists(path))
  return(path)
}

# set working directory
knitr::opts_knit$set(root.dir = user_path())

# setting github directory
github_path <- function() {
  user <- Sys.info()["user"]
  if (user == "asthavohra") {
    github = "/Users/asthavohra/Documents/GitHub/i-h2o-india/Code/2_Pilot/0_pilot logistics/"
  } 
  else if (user==""){
    github = ""
  } 
  else if (user == "") {
    github = ""
  } 
  else {
    warning("No path found for current user (", user, ")")
    github = getwd()
  }
  
  stopifnot(file.exists(github))
  return(github)
}

# setting google drive directory
gdrive_path <- function() {
  user <- Sys.info()["user"]
  if (user == "asthavohra") {
    gdrive = "/Volumes/GoogleDrive/Shared drives/DIL Shared Drive/DIL/Projects/Water/India/3_Field/2_Pilot/202306_June Pilot Planning"
  } 
  else if (user==""){
    gdrive = ""
  } 
  else if (user == "") {
    gdrive = ""
  } 
  else {
    warning("No path found for current user (", user, ")")
    gdrive = getwd()
  }
  
  stopifnot(file.exists(gdrive))
  return(gdrive)
}

```

```{r}
# Locally store the file

upload_df <- read_excel(paste0(user_path(), "ILC_India_GoogleSheet.xlsx"))

# Upload the file
googledrivedb <- paste0(gdrive_path(), "2-data")



# Connect to the google drive file database
con <-dbConnect(RSQLite::SQLite(), dbname = googledrivedb)

sheet_append(hh_randomization, ss = sheet_url, sheet = 2)



## Direct storage
# Create an empty spreadsheet. It is stored as an object with a sheet_id and drive_id 
ss <- gs4_create(name = "my_spreadsheet", sheets = "Sheet 1")

# Put the data.frame in the spreadsheet and provide the sheet_id so it can be found
sheet_write(data=, ss = ss, sheet ="Sheet 1")
dbDisconnect(con)

```

